# Generated by Django 3.1.4 on 2021-01-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccountsApp', '0004_auto_20201208_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AccountsApp.twofactortokens',),
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AccountsApp.twofactortokens',),
        ),
        migrations.RemoveField(
            model_name='verification',
            name='recovery',
        ),
        migrations.AddField(
            model_name='twofactortokens',
            name='provider',
            field=models.CharField(choices=[('email', 'Email'), ('otp', 'Otp')], default='email', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twofactortokens',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twofactortokens',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='twofactortokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('signature', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
