"""
Django settings for ContentAndSocialMediaSystem project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from typing import Any, Dict
from pathlib import Path
import django
from django.conf import settings

settings.configure(
    BASE_DIR = Path(__file__).resolve().parent.parent,

    SECRET_KEY = "g7pj-w#ix5e@ai59!_^yj4*#%ahjt$2u_h+#o=wdtm(1y&ozp5",

    APPEND_SLASH = True,

    SERVICE_CONTAINER = "",

    # Application definition

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'AccountsApp'
    ],

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ],

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ],
    LANGUAGE_CODE = 'en-us',

    TIME_ZONE = 'UTC',

    USE_I18N = True,

    USE_L10N = True,

    USE_TZ = True,

    ITEMS_PER_PAGE = 20,

    ACCOUNTS_APP = {
        "base_url": "accounts/",         # Base url pattern for the AccountsApp urls
        "redirect_link": '/dashboard/',    # Link redirected to after link verification 
        "code_length": 10,       # specifies the length of the verification code
        "sign_in_after_verification": True ,    # Specify if to sign in after verification is successful
        "2fa_duration": 2, # Validity period of 2fa tokens in minutes
        "reset_timeout": 10
    }
)
django.setup()